language: cpp
dist: xenial # используем Ubuntu Xenial 16.04
sudo: required # используем Virtual Machine (а не Docker container)
compiler:
    # ... и с помощью g++, и Clang
    - g++
    - clang

# установка необходимых зависимостей
# версию qt выбирается исходя https://launchpad.net/~beineri 
before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial -y
    - sudo apt-get update

install:
    - sudo apt-get install qt511base qt511charts-no-lgpl qt511xmlpatterns libqt5opengl5
    - source /opt/qt511/bin/qt511-env.sh
    - sudo apt-get install libusb-1.0-0-dev
    - sudo apt-get install -y xvfb
script:
    - /opt/qt511/bin/qmake PREFIX=/usr
    - make